import type { MockLocationsByLang } from './types';

export const UI_STRINGS = {
  english: {
    title: 'FarmAI Assistant',
    district: 'District',
    mandal: 'Mandal',
    village: 'Village',
    setLocation: 'Set Location',
    soilAndCrops: 'Soil & Suitable Crops',
    cropDoctor: 'Crop Doctor',
    marketInsights: 'Market Insights',
    govtSchemes: 'Government Schemes',
    govLinks: 'Govt. Links & Subsidies',
    nearbyTransport: 'Nearby Transportation',
    aiAssistant: 'AI Assistant',
    farmingMaterials: 'Farming Materials',
    fertilizerShops: 'Nearby Fertiliser Shops',
    villageMap: 'Village Map',
    coldStorages: 'Nearby Cold Storages',
    marketYards: 'Nearby Market Yards',
    setLocationPrompt: 'Please set your location in the header to get started.',
    modalTitles: {
      soil: 'Soil & Suitable Crops',
      doctor: 'Crop Doctor Analysis',
      market: 'Market Insights',
      schemes: 'Government Schemes',
      links: 'Government Links & Subsidies',
      transport: 'Nearby Transportation Services',
      assistant: 'AI Farming Assistant',
      materials: 'Farming Materials Guide',
      shops: 'Nearby Fertiliser Shops',
      map: 'Village Map',
      coldstorage: 'Nearby Cold Storages',
      marketyard: 'Nearby Market Yards',
    },
    // FIX: Add missing strings for location form button
    generateReport: 'Generate Report',
    generatingReport: 'Generating Report...',
    // New strings
    chatPlaceholder: 'Ask anything about farming...',
    send: 'Send',
    sources: 'Sources',
  },
  telugu: {
    title: 'ఫార్మ్ఏఐ అసిస్టెంట్',
    district: 'జిల్లా',
    mandal: 'మండలం',
    village: 'గ్రామం',
    setLocation: 'స్థానాన్ని సెట్ చేయండి',
    soilAndCrops: 'నేల & అనువైన పంటలు',
    cropDoctor: 'పంట వైద్యుడు',
    marketInsights: 'మార్కెట్ అంతర్దృష్టులు',
    govtSchemes: 'ప్రభుత్వ పథకాలు',
    govLinks: 'ప్రభుత్వ లింకులు & సబ్సిడీలు',
    nearbyTransport: 'సమీప రవాణా',
    aiAssistant: 'AI అసిస్టెంట్',
    farmingMaterials: 'వ్యవసాయ సామాగ్రి',
    fertilizerShops: ' సమీపంలోని ఎరువుల దుకాణాలు',
    villageMap: 'గ్రామ పటం',
    coldStorages: 'సమీపంలోని కోల్డ్ స్టోరేజీలు',
    marketYards: 'సమీపంలోని మార్కెట్ యార్డులు',
    setLocationPrompt: 'ప్రారంభించడానికి దయచేసి హెడర్‌లో మీ స్థానాన్ని సెట్ చేయండి.',
    modalTitles: {
      soil: 'నేల & అనువైన పంటలు',
      doctor: 'పంట వైద్యుని విశ్లేషణ',
      market: 'మార్కెట్ అంతర్దృష్టులు',
      schemes: 'ప్రభుత్వ పథకాలు',
      links: 'ప్రభుత్వ లింకులు & సబ్సిడీలు',
      transport: 'సమీప రవాణా సేవలు',
      assistant: 'AI వ్యవసాయ సహాయకుడు',
      materials: 'వ్యవసాయ సామాగ్రి గైడ్',
      shops: 'సమీపంలోని ఎరువుల దుకాణాలు',
      map: 'గ్రామ పటం',
      coldstorage: 'సమీపంలోని కోల్డ్ స్టోరేజీలు',
      marketyard: 'సమీపంలోని మార్కెట్ యార్డులు',
    },
    // FIX: Add missing strings for location form button
    generateReport: 'నివేదికను రూపొందించండి',
    generatingReport: 'నివేదికను రూపొందిస్తోంది...',
    // New strings
    chatPlaceholder: 'వ్యవసాయం గురించి ఏదైనా అడగండి...',
    send: 'పంపండి',
    sources: 'మూలాలు',
  },
};

export const MOCK_LOCATIONS: MockLocationsByLang = {
  english: [
    { district: 'Guntur', mandal: 'Tadikonda', village: 'Tadikonda' },
    { district: 'Guntur', mandal: 'Tadikonda', village: 'Lam' },
    { district: 'Guntur', mandal: 'Mangalagiri', village: 'Mangalagiri' },
    { district: 'Krishna', mandal: 'Gannavaram', village: 'Gannavaram' },
    { district: 'Krishna', mandal: 'Gannavaram', village: 'Kesarapalle' },
    { district: 'East Godavari', mandal: 'Rajahmundry Rural', village: 'Rajahmundry' },
    { district: 'East Godavari', mandal: 'Kadiam', village: 'Kadiam' },
  ],
  telugu: [
    { district: 'గుంటూరు', mandal: 'తాడికొండ', village: 'తాడికొండ' },
    { district: 'గుంటూరు', mandal: 'తాడికొండ', village: 'లాం' },
    { district: 'గుంటూరు', mandal: 'మంగళగిరి', village: 'మంగళగిరి' },
    { district: 'కృష్ణా', mandal: 'గన్నవరం', village: 'గన్నవరం' },
    { district: 'కృష్ణా', mandal: 'గన్నవరం', village: 'కేసరపల్లి' },
    { district: 'తూర్పు గోదావరి', mandal: 'రాజమండ్రి రూరల్', village: 'రాజమండ్రి' },
    { district: 'తూర్పు గోదావరి', mandal: 'కడియం', village: 'కడియం' },
  ],
};