import type { MockLocationsByLang } from './types';
import { 
    SoilIcon, DoctorIcon, MarketIcon, SchemeIcon, AIAssistantIcon, 
    FarmingMaterialsIcon, FertilizerShopsIcon, GovLinksIcon, TransportIcon, 
    SatelliteIcon, ColdStorageIcon, MarketYardIcon, WaterIcon, DroneIcon,
    FishIcon, FishDoctorIcon, AquaMarketIcon, AquaSchemeIcon, AquaEquipmentIcon, FeedHatcheryIcon
} from './components/icons';

export const UI_STRINGS = {
  english: {
    title: {
      agri: 'AGRIGUIDE',
      aqua: 'AQUAGUIDE',
    },
    district: 'District',
    mandal: 'Mandal',
    village: 'Village',
    constituency: 'Constituency',
    setLocation: 'Set Location',
    useCurrentLocation: 'Use Current Location',
    fetchingLocation: 'Fetching...',
    // Agri Features
    soilAndCrops: 'Soil & Suitable Crops',
    cropDoctor: 'Crop Doctor',
    marketInsights: 'Market Insights',
    govtSchemes: 'Government Schemes',
    farmingMaterials: 'Farming Materials',
    fertilizerShops: 'Nearby Fertiliser Shops',
    // Aqua Features
    waterAndSpecies: 'Water & Suitable Species',
    fishDoctor: 'Fish/Shrimp Doctor',
    aquaMarketInsights: 'Aqua Market Insights',
    aquaGovtSchemes: 'Aqua Schemes',
    aquaFarmingMaterials: 'Aqua Equipment',
    feedAndHatcheries: 'Nearby Feed & Hatcheries',
    // Common Features
    govLinks: 'Govt. Links & Subsidies',
    nearbyTransport: 'Nearby Transportation',
    aiAssistant: 'AI Assistant',
    villageMap: 'Satellite Village Map',
    coldStorages: 'Nearby Cold Storages',
    marketYards: 'Nearby Market Yards',
    nearbyWaterResources: 'Nearby Water Resources',
    droneDelivery: 'Drone Delivery Service',
    setLocationPrompt: 'Please set your location in the header to get started.',
    modalTitles: {
      soil: 'Analysis Report', // Generic now
      doctor: 'Doctor Analysis', // Generic now
      market: 'Market Insights', // Generic now
      schemes: 'Government Schemes', // Generic now
      links: 'Government Links & Subsidies',
      transport: 'Nearby Transportation Services',
      assistant: 'AI Assistant',
      materials: 'Equipment/Materials Guide', // Generic now
      shops: 'Nearby Shops', // Generic now
      map: 'Satellite Village Map',
      coldstorage: 'Nearby Cold Storages',
      marketyard: 'Nearby Market Yards',
      water: 'Nearby Water Resources',
      drone: 'Nearby Drone Delivery Services',
    },
    generateReport: 'Generate Report',
    generatingReport: 'Generating Report...',
    chatPlaceholder: 'Ask anything about farming or aquaculture...',
    send: 'Send',
    sources: 'Sources',
    // Weather strings
    currentWeather: 'Current Weather',
    forecast: '5-Day Forecast',
    humidity: 'Humidity',
    rain: 'Precipitation',
    wind: 'Wind',
    uvIndex: 'UV Index',
    fetchingWeather: 'Fetching weather...',
    weatherError: 'Could not fetch weather data.',
    feelsLike: 'Feels Like',
    windDirection: 'Wind Dir',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    hourlyForecast: 'Hourly Forecast',
    agriculturalAdvisory: 'Agricultural Advisory',
    // Booking strings
    availability: 'Availability',
    bookingInfo: 'Booking Information',
  },
  telugu: {
    title: {
      agri: 'అగ్రిగైడ్',
      aqua: 'ఆక్వాగైడ్',
    },
    district: 'జిల్లా',
    mandal: 'మండలం',
    village: 'గ్రామం',
    constituency: 'నియోజకవర్గం',
    setLocation: 'స్థానాన్ని సెట్ చేయండి',
    useCurrentLocation: 'ప్రస్తుత స్థానాన్ని ఉపయోగించండి',
    fetchingLocation: 'పొందుతోంది...',
    // Agri Features
    soilAndCrops: 'నేల & అనువైన పంటలు',
    cropDoctor: 'పంట వైద్యుడు',
    marketInsights: 'మార్కెట్ అంతర్దృష్టులు',
    govtSchemes: 'ప్రభుత్వ పథకాలు',
    farmingMaterials: 'వ్యవసాయ సామాగ్రి',
    fertilizerShops: ' సమీపంలోని ఎరువుల దుకాణాలు',
    // Aqua Features
    waterAndSpecies: 'నీరు & తగిన జాతులు',
    fishDoctor: 'చేప/రొయ్యల డాక్టర్',
    aquaMarketInsights: 'ఆక్వా మార్కెట్ అంతర్దృష్టులు',
    aquaGovtSchemes: 'ఆక్వా పథకాలు',
    aquaFarmingMaterials: 'ఆక్వా పరికరాలు',
    feedAndHatcheries: 'సమీపంలోని ఫీడ్ & హేచరీలు',
    // Common Features
    govLinks: 'ప్రభుత్వ లింకులు & సబ్సిడీలు',
    nearbyTransport: 'సమీప రవాణా',
    aiAssistant: 'AI అసిస్టెంట్',
    villageMap: 'శాటిలైట్ గ్రామ పటం',
    coldStorages: 'సమీపంలోని కోల్డ్ స్టోరేజీలు',
    marketYards: 'సమీపంలోని మార్కెట్ యార్డులు',
    nearbyWaterResources: 'సమీపంలోని నీటి వనరులు',
    droneDelivery: 'డ్రోన్ డెలివరీ సర్వీస్',
    setLocationPrompt: 'ప్రారంభించడానికి దయచేసి హెడర్‌లో మీ స్థానాన్ని సెట్ చేయండి.',
    modalTitles: {
      soil: 'విశ్లేషణ నివేదిక',
      doctor: 'డాక్టర్ విశ్లేషణ',
      market: 'మార్కెట్ అంతర్దృష్టులు',
      schemes: 'ప్రభుత్వ పథకాలు',
      links: 'ప్రభుత్వ లింకులు & సబ్సిడీలు',
      transport: 'సమీప రవాణా సేవలు',
      assistant: 'AI సహాయకుడు',
      materials: 'పరికరాలు/సామాగ్రి గైడ్',
      shops: 'సమీపంలోని దుకాణాలు',
      map: 'శాటిలైట్ గ్రామ పటం',
      coldstorage: 'సమీపంలోని కోల్డ్ స్టోరేజీలు',
      marketyard: 'సమీపంలోని మార్కెట్ యార్డులు',
      water: 'సమీపంలోని నీటి వనరులు',
      drone: 'సమీపంలోని డ్రోన్ డెలివరీ సేవలు',
    },
    generateReport: 'నివేదికను రూపొందించండి',
    generatingReport: 'నివేదికను రూపొందిస్తోంది...',
    chatPlaceholder: 'వ్యవసాయం లేదా ఆక్వాకల్చర్ గురించి ఏదైనా అడగండి...',
    send: 'పంపండి',
    sources: 'మూలాలు',
    // Weather strings
    currentWeather: 'ప్రస్తుత వాతావరణం',
    forecast: '5-రోజుల సూచన',
    humidity: 'తేమ',
    rain: 'అవపాతం',
    wind: 'గాలి',
    uvIndex: 'యూవీ సూచిక',
    fetchingWeather: 'వాతావరణ సమాచారం పొందుతోంది...',
    weatherError: 'వాతావరణ సమాచారాన్ని పొందడం సాధ్యం కాలేదు.',
    feelsLike: 'అనిపిస్తుంది',
    windDirection: 'గాలి దిశ',
    sunrise: 'సూర్యోదయం',
    sunset: 'సూర్యాస్తమయం',
    hourlyForecast: 'గంటలవారీ సూచన',
    agriculturalAdvisory: 'వ్యవసాయ సలహా',
    // Booking strings
    availability: 'లభ్యత',
    bookingInfo: 'బుకింగ్ సమాచారం',
  },
  hindi: {
    title: { agri: 'एग्रीगाइड', aqua: 'एक्वागाइड' },
    district: 'जिला',
    mandal: 'मंडल',
    village: 'गाँव',
    constituency: 'निर्वाचन क्षेत्र',
    setLocation: 'स्थान सेट करें',
    useCurrentLocation: 'वर्तमान स्थान का उपयोग करें',
    fetchingLocation: 'प्राप्त हो रहा है...',
    soilAndCrops: 'मिट्टी और उपयुक्त फसलें',
    cropDoctor: 'फसल डॉक्टर',
    marketInsights: 'बाजार की जानकारी',
    govtSchemes: 'सरकारी योजनाएं',
    farmingMaterials: 'खेती की सामग्री',
    fertilizerShops: 'आस-पास की उर्वरक दुकानें',
    waterAndSpecies: 'पानी और उपयुक्त प्रजातियाँ',
    fishDoctor: 'मछली/झींगा डॉक्टर',
    aquaMarketInsights: 'एक्वा बाजार की जानकारी',
    aquaGovtSchemes: 'एक्वा योजनाएं',
    aquaFarmingMaterials: 'एक्वा उपकरण',
    feedAndHatcheries: 'आस-पास के फ़ीड और हैचरी',
    govLinks: 'सरकारी लिंक और सब्सिडी',
    nearbyTransport: 'आस-पास परिवहन',
    aiAssistant: 'एआई सहायक',
    villageMap: 'सैटेलाइट ग्राम मानचित्र',
    coldStorages: 'आस-पास के कोल्ड स्टोरेज',
    marketYards: 'आस-पास के बाजार यार्ड',
    nearbyWaterResources: 'आस-पास के जल संसाधन',
    droneDelivery: 'ड्रोन डिलीवरी सेवा',
    setLocationPrompt: 'शुरू करने के लिए कृपया हेडर में अपना स्थान सेट करें।',
    modalTitles: {
      soil: 'विश्लेषण रिपोर्ट',
      doctor: 'डॉक्टर विश्लेषण',
      market: 'बाजार की जानकारी',
      schemes: 'सरकारी योजनाएं',
      links: 'सरकारी लिंक और सब्सिडी',
      transport: 'आस-पास परिवहन सेवाएं',
      assistant: 'एआई सहायक',
      materials: 'उपकरण/सामग्री गाइड',
      shops: 'आस-पास की दुकानें',
      map: 'सैटेलाइट ग्राम मानचित्र',
      coldstorage: 'आस-पास के कोल्ड स्टोरेज',
      marketyard: 'आस-पास के बाजार यार्ड',
      water: 'आस-पास के जल संसाधन',
      drone: 'आस-पास ड्रोन डिलीवरी सेवाएं',
    },
    generateReport: 'रिपोर्ट बनाएं',
    generatingReport: 'रिपोर्ट बन रही है...',
    chatPlaceholder: 'खेती या जलीय कृषि के बारे में कुछ भी पूछें...',
    send: 'भेजें',
    sources: 'स्रोत',
    currentWeather: 'वर्तमान मौसम',
    forecast: '5-दिन का पूर्वानुमान',
    humidity: 'आर्द्रता',
    rain: 'वर्षा',
    wind: 'हवा',
    uvIndex: 'यूवी इंडेक्स',
    fetchingWeather: 'मौसम की जानकारी मिल रही है...',
    weatherError: 'मौसम डेटा प्राप्त नहीं हो सका।',
    feelsLike: 'जैसा महसूस होता है',
    windDirection: 'हवा की दिशा',
    sunrise: 'सूर्योदय',
    sunset: 'सूर्यास्त',
    hourlyForecast: 'घंटे का पूर्वानुमान',
    agriculturalAdvisory: 'कृषि सलाह',
    availability: 'उपलब्धता',
    bookingInfo: 'बुकिंग जानकारी',
  },
  kannada: {
    title: { agri: 'ಅಗ್ರಿ-ಗೈಡ್', aqua: 'ಆಕ್ವಾ-ಗೈಡ್' },
    district: 'ಜಿಲ್ಲೆ',
    mandal: 'ತಾಲೂಕು',
    village: 'ಗ್ರಾಮ',
    constituency: 'ಕ್ಷೇತ್ರ',
    setLocation: 'ಸ್ಥಳವನ್ನು ಹೊಂದಿಸಿ',
    useCurrentLocation: 'ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಬಳಸಿ',
    fetchingLocation: 'ಪಡೆಯುತ್ತಿದೆ...',
    soilAndCrops: 'ಮಣ್ಣು ಮತ್ತು ಸೂಕ್ತ ಬೆಳೆಗಳು',
    cropDoctor: 'ಬೆಳೆ ವೈದ್ಯರು',
    marketInsights: 'ಮಾರುಕಟ್ಟೆ ಒಳನೋಟಗಳು',
    govtSchemes: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    farmingMaterials: 'ಕೃಷಿ ಸಾಮಗ್ರಿಗಳು',
    fertilizerShops: 'ಹತ್ತಿರದ ರಸಗೊಬ್ಬರ ಅಂಗಡಿಗಳು',
    waterAndSpecies: 'ನೀರು ಮತ್ತು ಸೂಕ್ತ ಪ್ರಭೇದಗಳು',
    fishDoctor: 'ಮೀನು/ಸೀಗಡಿ ವೈದ್ಯರು',
    aquaMarketInsights: 'ಆಕ್ವಾ ಮಾರುಕಟ್ಟೆ ಒಳನೋಟಗಳು',
    aquaGovtSchemes: 'ಆಕ್ವಾ ಯೋಜನೆಗಳು',
    aquaFarmingMaterials: 'ಆಕ್ವಾ ಉಪಕರಣಗಳು',
    feedAndHatcheries: 'ಹತ್ತಿರದ ಫೀಡ್ ಮತ್ತು ಹ್ಯಾಚರಿಗಳು',
    govLinks: 'ಸರ್ಕಾರಿ ಲಿಂಕ್‌ಗಳು ಮತ್ತು ಸಬ್ಸಿಡಿಗಳು',
    nearbyTransport: 'ಹತ್ತಿರದ ಸಾರಿಗೆ',
    aiAssistant: 'AI ಸಹಾಯಕ',
    villageMap: 'ಉಪಗ್ರಹ ಗ್ರಾಮ ನಕ್ಷೆ',
    coldStorages: 'ಹತ್ತಿರದ ಶೀತಲಗೃಹಗಳು',
    marketYards: 'ಹತ್ತಿರದ ಮಾರುಕಟ್ಟೆ ಯಾರ್ಡ್‌ಗಳು',
    nearbyWaterResources: 'ಹತ್ತಿರದ ಜಲ ಸಂಪನ್ಮೂಲಗಳು',
    droneDelivery: 'ಡ್ರೋನ್ ವಿತರಣಾ ಸೇವೆ',
    setLocationPrompt: 'ಪ್ರಾರಂಭಿಸಲು ದಯವಿಟ್ಟು ಹೆಡರ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಹೊಂದಿಸಿ.',
    modalTitles: {
      soil: 'ವಿಶ್ಲೇಷಣೆ ವರದಿ',
      doctor: 'ವೈದ್ಯರ ವಿಶ್ಲೇಷಣೆ',
      market: 'ಮಾರುಕಟ್ಟೆ ಒಳನೋಟಗಳು',
      schemes: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
      links: 'ಸರ್ಕಾರಿ ಲಿಂಕ್‌ಗಳು ಮತ್ತು ಸಬ್ಸಿಡಿಗಳು',
      transport: 'ಹತ್ತಿರದ ಸಾರಿಗೆ ಸೇವೆಗಳು',
      assistant: 'AI ಸಹಾಯಕ',
      materials: 'ಉಪಕರಣ/ಸಾಮಗ್ರಿ ಮಾರ್ಗದರ್ಶಿ',
      shops: 'ಹತ್ತಿರದ ಅಂಗಡಿಗಳು',
      map: 'ಉಪಗ್ರಹ ಗ್ರಾಮ ನಕ್ಷೆ',
      coldstorage: 'ಹತ್ತಿರದ ಶೀತಲಗೃಹಗಳು',
      marketyard: 'ಹತ್ತಿರದ ಮಾರುಕಟ್ಟೆ ಯಾರ್ಡ್‌ಗಳು',
      water: 'ಹತ್ತಿರದ ಜಲ ಸಂಪನ್ಮೂಲಗಳು',
      drone: 'ಹತ್ತಿರದ ಡ್ರೋನ್ ವಿತರಣಾ ಸೇವೆಗಳು',
    },
    generateReport: 'ವರದಿ ರಚಿಸಿ',
    generatingReport: 'ವರದಿ ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    chatPlaceholder: 'ಕೃಷಿ ಅಥವಾ ಜಲಚರ ಸಾಕಾಣಿಕೆ ಬಗ್ಗೆ что-нибудь ಕೇಳಿ...',
    send: 'ಕಳುಹಿಸಿ',
    sources: 'ಮೂಲಗಳು',
    currentWeather: 'ಪ್ರಸ್ತುತ ಹವಾಮಾನ',
    forecast: '5-ದಿನದ ಮುನ್ಸೂಚನೆ',
    humidity: 'ಆರ್ದ್ರತೆ',
    rain: 'ಮಳೆ',
    wind: 'ಗಾಳಿ',
    uvIndex: 'ಯುವಿ ಸೂಚ್ಯಂಕ',
    fetchingWeather: 'ಹವಾಮಾನ ಪಡೆಯಲಾಗುತ್ತಿದೆ...',
    weatherError: 'ಹವಾಮಾನ ಡೇಟಾವನ್ನು ಪಡೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
    feelsLike: 'ಅನುಭವ',
    windDirection: 'ಗಾಳಿಯ ದಿಕ್ಕು',
    sunrise: 'ಸೂರ್ಯೋದಯ',
    sunset: 'ಸೂರ್ಯಾಸ್ತ',
    hourlyForecast: 'ಗಂಟೆಯ ಮುನ್ಸೂಚನೆ',
    agriculturalAdvisory: 'ಕೃಷಿ ಸಲಹೆ',
    availability: 'ಲಭ್ಯತೆ',
    bookingInfo: 'ಬುಕಿಂಗ್ ಮಾಹಿತಿ',
  },
  tamil: {
    title: { agri: 'அக்ரி-கைடு', aqua: 'அக்வா-கைடு' },
    district: 'மாவட்டம்',
    mandal: 'மண்டலம்',
    village: 'கிராமம்',
    constituency: 'தொகுதி',
    setLocation: 'இடத்தை அமைக்கவும்',
    useCurrentLocation: 'தற்போதைய இடத்தைப் பயன்படுத்தவும்',
    fetchingLocation: 'பெறப்படுகிறது...',
    soilAndCrops: 'மண் மற்றும் பொருத்தமான பயிர்கள்',
    cropDoctor: 'பயிர் மருத்துவர்',
    marketInsights: 'சந்தை நுண்ணறிவு',
    govtSchemes: 'அரசு திட்டங்கள்',
    farmingMaterials: 'விவசாயப் பொருட்கள்',
    fertilizerShops: 'அருகிலுள்ள உரக் கடைகள்',
    waterAndSpecies: 'நீர் மற்றும் பொருத்தமான இனங்கள்',
    fishDoctor: 'மீன்/இறால் மருத்துவர்',
    aquaMarketInsights: 'அக்வா சந்தை நுண்ணறிவு',
    aquaGovtSchemes: 'அக்வா திட்டங்கள்',
    aquaFarmingMaterials: 'அக்வா உபகரணங்கள்',
    feedAndHatcheries: 'அருகிலுள்ள தீவனம் மற்றும் குஞ்சுபொரிப்பகங்கள்',
    govLinks: 'அரசு இணைப்புகள் மற்றும் மானியங்கள்',
    nearbyTransport: 'அருகிலுள்ள போக்குவரத்து',
    aiAssistant: 'AI உதவியாளர்',
    villageMap: 'செயற்கைக்கோள் கிராம வரைபடம்',
    coldStorages: 'அருகிலுள்ள குளிர்பதனக் கிடங்குகள்',
    marketYards: 'அருகிலுள்ள சந்தைகள்',
    nearbyWaterResources: 'அருகிலுள்ள நீர் ஆதாரங்கள்',
    droneDelivery: 'ட்ரோன் விநியோக சேவை',
    setLocationPrompt: 'தொடங்க, தயவுசெய்து தலைப்பில் உங்கள் இருப்பிடத்தை அமைக்கவும்.',
    modalTitles: {
      soil: 'பகுப்பாய்வு அறிக்கை',
      doctor: 'மருத்துவர் பகுப்பாய்வு',
      market: 'சந்தை நுண்ணறிவு',
      schemes: 'அரசு திட்டங்கள்',
      links: 'அரசு இணைப்புகள் மற்றும் மானியங்கள்',
      transport: 'அருகிலுள்ள போக்குவரத்து சேவைகள்',
      assistant: 'AI உதவியாளர்',
      materials: 'உபகரணங்கள்/பொருட்கள் வழிகாட்டி',
      shops: 'அருகிலுள்ள கடைகள்',
      map: 'செயற்கைக்கோள் கிராம வரைபடம்',
      coldstorage: 'அருகிலுள்ள குளிர்பதனக் கிடங்குகள்',
      marketyard: 'அருகிலுள்ள சந்தைகள்',
      water: 'அருகிலுள்ள நீர் ஆதாரங்கள்',
      drone: 'அருகிலுள்ள ட்ரோன் விநியோக சேவைகள்',
    },
    generateReport: 'அறிக்கையை உருவாக்கவும்',
    generatingReport: 'அறிக்கை உருவாக்கப்படுகிறது...',
    chatPlaceholder: 'விவசாயம் அல்லது நீர்வாழ் உயிரின வளர்ப்பு பற்றி எதுவும் கேளுங்கள்...',
    send: 'அனுப்பு',
    sources: 'ஆதாரங்கள்',
    currentWeather: 'தற்போதைய வானிலை',
    forecast: '5-நாள் முன்னறிவிப்பு',
    humidity: 'ஈரப்பதம்',
    rain: 'மழைப்பொழிவு',
    wind: 'காற்று',
    uvIndex: 'புற ஊதா குறியீடு',
    fetchingWeather: 'வானிலை எடுக்கப்படுகிறது...',
    weatherError: 'வானிலை தரவைப் பெற முடியவில்லை.',
    feelsLike: 'உணர்வது போல்',
    windDirection: 'காற்றின் திசை',
    sunrise: 'சூரிய உதயம்',
    sunset: 'சூரிய அஸ்தமனம்',
    hourlyForecast: 'மணிநேர முன்னறிவிப்பு',
    agriculturalAdvisory: 'விவசாய ஆலோசனை',
    availability: 'கிடைக்கும்',
    bookingInfo: 'முன்பதிவு தகவல்',
  },
  malayalam: {
    title: { agri: 'അഗ്രി-ഗൈഡ്', aqua: 'അക്വാ-ഗൈഡ്' },
    district: 'ജില്ല',
    mandal: 'മണ്ഡലം',
    village: 'ഗ്രാമം',
    constituency: 'നിയോജകമണ്ഡലം',
    setLocation: 'സ്ഥലം സജ്ജമാക്കുക',
    useCurrentLocation: 'നിലവിലെ സ്ഥലം ഉപയോഗിക്കുക',
    fetchingLocation: 'ലഭിക്കുന്നു...',
    soilAndCrops: 'മണ്ണും അനുയോജ്യമായ വിളകളും',
    cropDoctor: 'വിള ഡോക്ടർ',
    marketInsights: 'വിപണി ഉൾക്കാഴ്ചകൾ',
    govtSchemes: 'സർക്കാർ പദ്ധതികൾ',
    farmingMaterials: 'കൃഷി സാമഗ്രികൾ',
    fertilizerShops: 'അടുത്തുള്ള വളം കടകൾ',
    waterAndSpecies: 'വെള്ളവും അനുയോജ്യമായ ജീവികളും',
    fishDoctor: 'മത്സ്യം/ചെമ്മീൻ ഡോക്ടർ',
    aquaMarketInsights: 'അക്വാ വിപണി ഉൾക്കാഴ്ചകൾ',
    aquaGovtSchemes: 'അക്വാ പദ്ധതികൾ',
    aquaFarmingMaterials: 'അക്വാ ഉപകരണങ്ങൾ',
    feedAndHatcheries: 'അടുത്തുള്ള ഫീഡും ഹാച്ചറികളും',
    govLinks: 'സർക്കാർ ലിങ്കുകളും സബ്സിഡികളും',
    nearbyTransport: 'അടുത്തുള്ള ഗതാഗതം',
    aiAssistant: 'AI അസിസ്റ്റന്റ്',
    villageMap: 'ഉപഗ്രഹ ഗ്രാമ ഭൂപടം',
    coldStorages: 'അടുത്തുള്ള കോൾഡ് സ്റ്റോറേജുകൾ',
    marketYards: 'അടുത്തുള്ള മാർക്കറ്റ് യാർഡുകൾ',
    nearbyWaterResources: 'അടുത്തുള്ള ജലസ്രോതസ്സുകൾ',
    droneDelivery: 'ഡ്രോൺ ഡെലിവറി സേവനം',
    setLocationPrompt: 'തുടങ്ങുന്നതിന് ദയവായി തലക്കെട്ടിൽ നിങ്ങളുടെ സ്ഥലം സജ്ജമാക്കുക.',
    modalTitles: {
      soil: 'വിശകലന റിപ്പോർട്ട്',
      doctor: 'ഡോക്ടർ വിശകലനം',
      market: 'വിപണി ഉൾക്കാഴ്ചകൾ',
      schemes: 'സർക്കാർ പദ്ധതികൾ',
      links: 'സർക്കാർ ലിങ്കുകളും സബ്സിഡികളും',
      transport: 'അടുത്തുള്ള ഗതാഗത സേവനങ്ങൾ',
      assistant: 'AI അസിസ്റ്റന്റ്',
      materials: 'ഉപകരണങ്ങൾ/സാമഗ്രികൾ ഗൈഡ്',
      shops: 'അടുത്തുള്ള കടകൾ',
      map: 'ഉപഗ്രഹ ഗ്രാമ ഭൂപടം',
      coldstorage: 'അടുത്തുള്ള കോൾഡ് സ്റ്റോറേജുകൾ',
      marketyard: 'അടുത്തുള്ള മാർക്കറ്റ് യാർഡുകൾ',
      water: 'അടുത്തുള്ള ജലസ്രോതസ്സുകൾ',
      drone: 'അടുത്തുള്ള ഡ്രോൺ ഡെലിവറി സേവനങ്ങൾ',
    },
    generateReport: 'റിപ്പോർട്ട് ഉണ്ടാക്കുക',
    generatingReport: 'റിപ്പോർട്ട് ഉണ്ടാക്കുന്നു...',
    chatPlaceholder: 'കൃഷിയെക്കുറിച്ചോ ജലകൃഷിയെക്കുറിച്ചോ എന്തെങ്കിലും ചോദിക്കുക...',
    send: 'അയയ്ക്കുക',
    sources: 'ഉറവിടങ്ങൾ',
    currentWeather: 'നിലവിലെ കാലാവസ്ഥ',
    forecast: '5-ദിവസത്തെ പ്രവചനം',
    humidity: 'ഈർപ്പം',
    rain: 'മഴ',
    wind: 'കാറ്റ്',
    uvIndex: 'യുവി സൂചിക',
    fetchingWeather: 'കാലാവസ്ഥ ലഭ്യമാക്കുന്നു...',
    weatherError: 'കാലാവസ്ഥാ ഡാറ്റ ലഭ്യമല്ല.',
    feelsLike: 'അനുഭവപ്പെടുന്നു',
    windDirection: 'കാറ്റിന്റെ ദിശ',
    sunrise: 'സൂര്യോദയം',
    sunset: 'സൂര്യാസ്തമയം',
    hourlyForecast: 'മണിക്കൂർ പ്രവചനം',
    agriculturalAdvisory: 'കാർഷിക ഉപദേശം',
    availability: 'ലഭ്യത',
    bookingInfo: 'ബുക്കിംഗ് വിവരം',
  },
  marathi: {
    title: { agri: 'अ‍ॅग्री-गाईड', aqua: 'अ‍ॅक्वा-गाईड' },
    district: 'जिल्हा',
    mandal: 'तालुका',
    village: 'गाव',
    constituency: 'मतदारसंघ',
    setLocation: 'स्थान सेट करा',
    useCurrentLocation: 'सध्याचे स्थान वापरा',
    fetchingLocation: 'आणत आहे...',
    soilAndCrops: 'माती आणि योग्य पिके',
    cropDoctor: 'पीक डॉक्टर',
    marketInsights: 'बाजारपेठेतील अंतर्दृष्टी',
    govtSchemes: 'सरकारी योजना',
    farmingMaterials: 'शेती साहित्य',
    fertilizerShops: 'जवळची खतांची दुकाने',
    waterAndSpecies: 'पाणी आणि योग्य प्रजाती',
    fishDoctor: 'मासे/कोळंबी डॉक्टर',
    aquaMarketInsights: 'जलबाजारपेठेतील अंतर्दृष्टी',
    aquaGovtSchemes: 'जल योजना',
    aquaFarmingMaterials: 'जल उपकरणे',
    feedAndHatcheries: 'जवळचे फीड आणि हॅचरी',
    govLinks: 'सरकारी दुवे आणि सबसिडी',
    nearbyTransport: 'जवळची वाहतूक',
    aiAssistant: 'एआय सहाय्यक',
    villageMap: 'उपग्रह गाव नकाशा',
    coldStorages: 'जवळची शीतगृहे',
    marketYards: 'जवळचे मार्केट यार्ड',
    nearbyWaterResources: 'जवळचे जलस्रोत',
    droneDelivery: 'ड्रोन वितरण सेवा',
    setLocationPrompt: 'सुरू करण्यासाठी कृपया शीर्षलेखात आपले स्थान सेट करा.',
    modalTitles: {
      soil: 'विश्लेषण अहवाल',
      doctor: 'डॉक्टर विश्लेषण',
      market: 'बाजारपेठेतील अंतर्दृष्टी',
      schemes: 'सरकारी योजना',
      links: 'सरकारी दुवे आणि सबसिडी',
      transport: 'जवळच्या वाहतूक सेवा',
      assistant: 'एआय सहाय्यक',
      materials: 'उपकरणे/साहित्य मार्गदर्शक',
      shops: 'जवळची दुकाने',
      map: 'उपग्रह गाव नकाशा',
      coldstorage: 'जवळची शीतगृहे',
      marketyard: 'जवळचे मार्केट यार्ड',
      water: 'जवळचे जलस्रोत',
      drone: 'जवळच्या ड्रोन वितरण सेवा',
    },
    generateReport: 'अहवाल तयार करा',
    generatingReport: 'अहवाल तयार होत आहे...',
    chatPlaceholder: 'शेती किंवा जलशेतीबद्दल काहीही विचारा...',
    send: 'पाठवा',
    sources: 'स्रोत',
    currentWeather: 'सध्याचे हवामान',
    forecast: '5-दिवसांचा अंदाज',
    humidity: 'आर्द्रता',
    rain: 'पर्जन्य',
    wind: 'वारा',
    uvIndex: 'यूव्ही निर्देशांक',
    fetchingWeather: 'हवामान आणत आहे...',
    weatherError: 'हवामान डेटा मिळू शकला नाही.',
    feelsLike: 'जाणवते',
    windDirection: 'वाऱ्याची दिशा',
    sunrise: 'सूर्योदय',
    sunset: 'सूर्यास्त',
    hourlyForecast: 'तासाभराचा अंदाज',
    agriculturalAdvisory: 'कृषी सल्ला',
    availability: 'उपलब्धता',
    bookingInfo: 'बुकिंग माहिती',
  }
};

export const AGRI_MOCK_LOCATIONS: MockLocationsByLang = {
  english: [
    { district: 'Anakapalli', mandal: 'Anakapalli', village: 'Anakapalli' },
    { district: 'Kakinada', mandal: 'Pithapuram', village: 'Pithapuram' },
    { district: 'NTR', mandal: 'Vijayawada (Urban)', village: 'Vijayawada' },
  ],
  telugu: [
    { district: 'అనకాపల్లి', mandal: 'అనకాపల్లి', village: 'అనకాపల్లి' },
    { district: 'కాకినాడ', mandal: 'పిఠాపురం', village: 'పిఠాపురం' },
    { district: 'ఎన్టీఆర్', mandal: 'విజయవాడ (పట్టణ)', village: 'విజయవాడ' },
  ],
  hindi: [
    { district: 'लखनऊ', mandal: 'मोहनलालगंज', village: 'मोहनलालगंज' },
    { district: 'भोपाल', mandal: 'हुज़ूर', village: 'हुज़ूर' },
    { district: 'जयपुर', mandal: 'सांगानेर', village: 'सांगानेर' },
  ],
  kannada: [
    { district: 'ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ', mandal: 'ದೊಡ್ಡಬಳ್ಳಾಪುರ', village: 'ದೊಡ್ಡಬಳ್ಳಾಪುರ' },
    { district: 'ಮೈಸೂರು', mandal: 'ನಂಜನಗೂಡು', village: 'ನಂಜನಗೂಡು' },
    { district: 'ಧಾರವಾಡ', mandal: 'ಧಾರವಾಡ', village: 'ಧಾರವಾಡ' },
  ],
  tamil: [
    { district: 'கோயம்புத்தூர்', mandal: 'பொள்ளாச்சி', village: 'பொள்ளாச்சி' },
    { district: 'மதுரை', mandal: 'மேலூர்', village: 'மேலூர்' },
    { district: 'திருநெல்வேலி', mandal: 'பாளையங்கோட்டை', village: 'பாளையங்கோட்டை' },
  ],
  malayalam: [
    { district: 'പാലക്കാട്', mandal: 'ആലത്തൂർ', village: 'ആലത്തൂർ' },
    { district: 'തൃശ്ശൂർ', mandal: 'ചാലക്കുടി', village: 'ചാലക്കുടി' },
    { district: 'കോട്ടയം', mandal: 'കാഞ്ഞിരപ്പള്ളി', village: 'കാഞ്ഞിരപ്പള്ളി' },
  ],
  marathi: [
    { district: 'पुणे', mandal: 'हवेली', village: 'हवेली' },
    { district: 'नाशिक', mandal: 'नाशिक', village: 'नाशिक' },
    { district: 'नागपूर', mandal: 'नागपूर (ग्रामीण)', village: 'नागपूर' },
  ]
};

export const AQUA_MOCK_LOCATIONS: MockLocationsByLang = {
  english: [
    { district: 'Kakinada', constituency: 'Kakinada Rural' },
    { district: 'Konaseema', constituency: 'Amalapuram' },
    { district: 'Nellore', constituency: 'Kovur' },
  ],
  telugu: [
    { district: 'కాకినాడ', constituency: 'కాకినాడ గ్రామీణ' },
    { district: 'కోనసీమ', constituency: 'అమలాపురం' },
    { district: 'నెల్లూరు', constituency: 'కోవూరు' },
  ],
  hindi: [
    { district: 'रायबरेली', constituency: 'रायबरेली' },
    { district: 'सुल्तानपुर', constituency: 'सुल्तानपुर' },
    { district: 'प्रयागराज', constituency: 'इलाहाबाद' },
  ],
  kannada: [
    { district: 'ಉಡುಪಿ', constituency: 'ಉಡುಪಿ' },
    { district: 'ದಕ್ಷಿಣ ಕನ್ನಡ', constituency: 'ಮಂಗಳೂರು' },
    { district: 'ಕಾರವಾರ', constituency: 'ಕಾರವಾರ' },
  ],
  tamil: [
    { district: 'நாகப்பட்டினம்', constituency: 'நாகப்பட்டினம்' },
    { district: 'கடலூர்', constituency: 'கடலூர்' },
    { district: 'தூத்துக்குடி', constituency: 'தூத்துக்குடி' },
  ],
  malayalam: [
    { district: 'ആലപ്പുഴ', constituency: 'അമ്പലപ്പുഴ' },
    { district: 'എറണാകുളം', constituency: 'എറണാകുളം' },
    { district: 'കൊല്ലം', constituency: 'കൊല്ലം' },
  ],
  marathi: [
    { district: 'रत्नागिरी', constituency: 'रत्नागिरी' },
    { district: 'सिंधुदुर्ग', constituency: 'सिंधुदुर्ग' },
    { district: 'रायगड', constituency: 'रायगड' },
  ]
};


export const FEATURES = {
    agri: [
        { id: 'soil', icon: SoilIcon, titleKey: 'soilAndCrops' },
        { id: 'doctor', icon: DoctorIcon, titleKey: 'cropDoctor' },
        { id: 'market', icon: MarketIcon, titleKey: 'marketInsights' },
        { id: 'schemes', icon: SchemeIcon, titleKey: 'govtSchemes' },
        { id: 'assistant', icon: AIAssistantIcon, titleKey: 'aiAssistant' },
        { id: 'materials', icon: FarmingMaterialsIcon, titleKey: 'farmingMaterials' },
        { id: 'shops', icon: FertilizerShopsIcon, titleKey: 'fertilizerShops' },
        { id: 'links', icon: GovLinksIcon, titleKey: 'govLinks' },
        { id: 'transport', icon: TransportIcon, titleKey: 'nearbyTransport' },
        { id: 'map', icon: SatelliteIcon, titleKey: 'villageMap' },
        { id: 'coldstorage', icon: ColdStorageIcon, titleKey: 'coldStorages' },
        { id: 'marketyard', icon: MarketYardIcon, titleKey: 'marketYards' },
        { id: 'water', icon: WaterIcon, titleKey: 'nearbyWaterResources' },
        { id: 'drone', icon: DroneIcon, titleKey: 'droneDelivery' },
    ],
    aqua: [
        { id: 'soil', icon: FishIcon, titleKey: 'waterAndSpecies' },
        { id: 'doctor', icon: FishDoctorIcon, titleKey: 'fishDoctor' },
        { id: 'market', icon: AquaMarketIcon, titleKey: 'aquaMarketInsights' },
        { id: 'schemes', icon: AquaSchemeIcon, titleKey: 'aquaGovtSchemes' },
        { id: 'assistant', icon: AIAssistantIcon, titleKey: 'aiAssistant' },
        { id: 'materials', icon: AquaEquipmentIcon, titleKey: 'aquaFarmingMaterials' },
        { id: 'shops', icon: FeedHatcheryIcon, titleKey: 'feedAndHatcheries' },
        { id: 'links', icon: GovLinksIcon, titleKey: 'govLinks' },
        { id: 'transport', icon: TransportIcon, titleKey: 'nearbyTransport' },
        { id: 'map', icon: SatelliteIcon, titleKey: 'villageMap' },
        { id: 'coldstorage', icon: ColdStorageIcon, titleKey: 'coldStorages' },
        { id: 'marketyard', icon: MarketYardIcon, titleKey: 'marketYards' },
        { id: 'water', icon: WaterIcon, titleKey: 'nearbyWaterResources' },
        { id: 'drone', icon: DroneIcon, titleKey: 'droneDelivery' },
    ],
};

export const PRIMARY_FEATURES = {
    agri: ['doctor', 'market', 'soil'],
    aqua: ['doctor', 'market', 'soil'], // 'soil' is 'Water & Species' in aqua mode
};
