import type { MockLocationsByLang } from './types';

export const UI_STRINGS = {
  english: {
    title: 'AGRIGUIDE',
    district: 'District',
    mandal: 'Mandal',
    village: 'Village',
    setLocation: 'Set Location',
    useCurrentLocation: 'Use Current Location',
    fetchingLocation: 'Fetching...',
    soilAndCrops: 'Soil & Suitable Crops',
    cropDoctor: 'Crop Doctor',
    marketInsights: 'Market Insights',
    govtSchemes: 'Government Schemes',
    govLinks: 'Govt. Links & Subsidies',
    nearbyTransport: 'Nearby Transportation',
    aiAssistant: 'AI Assistant',
    farmingMaterials: 'Farming Materials',
    fertilizerShops: 'Nearby Fertiliser Shops',
    villageMap: 'Satellite Village Map',
    coldStorages: 'Nearby Cold Storages',
    marketYards: 'Nearby Market Yards',
    nearbyWaterResources: 'Nearby Water Resources',
    droneDelivery: 'Drone Delivery Service',
    setLocationPrompt: 'Please set your location in the header to get started.',
    modalTitles: {
      soil: 'Soil & Suitable Crops',
      doctor: 'Crop Doctor Analysis',
      market: 'Market Insights',
      schemes: 'Government Schemes',
      links: 'Government Links & Subsidies',
      transport: 'Nearby Transportation Services',
      assistant: 'AI Farming Assistant',
      materials: 'Farming Materials Guide',
      shops: 'Nearby Fertiliser Shops',
      map: 'Satellite Village Map',
      coldstorage: 'Nearby Cold Storages',
      marketyard: 'Nearby Market Yards',
      water: 'Nearby Water Resources',
      drone: 'Nearby Drone Delivery Services',
    },
    // FIX: Add missing strings for location form button
    generateReport: 'Generate Report',
    generatingReport: 'Generating Report...',
    // New strings
    chatPlaceholder: 'Ask anything about farming...',
    send: 'Send',
    sources: 'Sources',
    // Weather strings
    currentWeather: 'Current Weather',
    forecast: '3-Day Forecast',
    humidity: 'Humidity',
    rain: 'Precipitation',
    wind: 'Wind',
    uvIndex: 'UV Index',
    fetchingWeather: 'Fetching weather...',
    weatherError: 'Could not fetch weather data.',
    // Booking strings
    availability: 'Availability',
    bookingInfo: 'Booking Information',
  },
  telugu: {
    title: 'అగ్రిగైడ్',
    district: 'జిల్లా',
    mandal: 'మండలం',
    village: 'గ్రామం',
    setLocation: 'స్థానాన్ని సెట్ చేయండి',
    useCurrentLocation: 'ప్రస్తుత స్థానాన్ని ఉపయోగించండి',
    fetchingLocation: 'పొందుతోంది...',
    soilAndCrops: 'నేల & అనువైన పంటలు',
    cropDoctor: 'పంట వైద్యుడు',
    marketInsights: 'మార్కెట్ అంతర్దృష్టులు',
    govtSchemes: 'ప్రభుత్వ పథకాలు',
    govLinks: 'ప్రభుత్వ లింకులు & సబ్సిడీలు',
    nearbyTransport: 'సమీప రవాణా',
    aiAssistant: 'AI అసిస్టెంట్',
    farmingMaterials: 'వ్యవసాయ సామాగ్రి',
    fertilizerShops: ' సమీపంలోని ఎరువుల దుకాణాలు',
    villageMap: 'శాటిలైట్ గ్రామ పటం',
    coldStorages: 'సమీపంలోని కోల్డ్ స్టోరేజీలు',
    marketYards: 'సమీపంలోని మార్కెట్ యార్డులు',
    nearbyWaterResources: 'సమీపంలోని నీటి వనరులు',
    droneDelivery: 'డ్రోన్ డెలివరీ సర్వీస్',
    setLocationPrompt: 'ప్రారంభించడానికి దయచేసి హెడర్‌లో మీ స్థానాన్ని సెట్ చేయండి.',
    modalTitles: {
      soil: 'నేల & అనువైన పంటలు',
      doctor: 'పంట వైద్యుని విశ్లేషణ',
      market: 'మార్కెట్ అంతర్దృష్టులు',
      schemes: 'ప్రభుత్వ పథకాలు',
      links: 'ప్రభుత్వ లింకులు & సబ్సిడీలు',
      transport: 'సమీప రవాణా సేవలు',
      assistant: 'AI వ్యవసాయ సహాయకుడు',
      materials: 'వ్యవసాయ సామాగ్రి గైడ్',
      shops: 'సమీపంలోని ఎరువుల దుకాణాలు',
      map: 'శాటిలైట్ గ్రామ పటం',
      coldstorage: 'సమీపంలోని కోల్డ్ స్టోరేజీలు',
      marketyard: 'సమీపంలోని మార్కెట్ యార్డులు',
      water: 'సమీపంలోని నీటి వనరులు',
      drone: 'సమీపంలోని డ్రోన్ డెలివరీ సేవలు',
    },
    // FIX: Add missing strings for location form button
    generateReport: 'నివేదికను రూపొందించండి',
    generatingReport: 'నివేదికను రూపొందిస్తోంది...',
    // New strings
    chatPlaceholder: 'వ్యవసాయం గురించి ఏదైనా అడగండి...',
    send: 'పంపండి',
    sources: 'మూలాలు',
    // Weather strings
    currentWeather: 'ప్రస్తుత వాతావరణం',
    forecast: '3-రోజుల సూచన',
    humidity: 'తేమ',
    rain: 'అవపాతం',
    wind: 'గాలి',
    uvIndex: 'యూవీ సూచిక',
    fetchingWeather: 'వాతావరణ సమాచారం పొందుతోంది...',
    weatherError: 'వాతావరణ సమాచారాన్ని పొందడం సాధ్యం కాలేదు.',
    // Booking strings
    availability: 'లభ్యత',
    bookingInfo: 'బుకింగ్ సమాచారం',
  },
};

export const MOCK_LOCATIONS: MockLocationsByLang = {
  english: [
    { district: 'Anakapalli', mandal: 'Anakapalli', village: 'Anakapalli' },
    { district: 'Anakapalli', mandal: 'Yelamanchili', village: 'Yelamanchili' },
    { district: 'Kakinada', mandal: 'Kakinada (Urban)', village: 'Kakinada' },
    { district: 'Kakinada', mandal: 'Pithapuram', village: 'Pithapuram' },
    { district: 'NTR', mandal: 'Vijayawada (Urban)', village: 'Vijayawada' },
    { district: 'NTR', mandal: 'Tiruvuru', village: 'Tiruvuru' },
    { district: 'Palnadu', mandal: 'Narasaraopet', village: 'Narasaraopet' },
    { district: 'Tirupati', mandal: 'Tirupati (Urban)', village: 'Tirupati' },
    { district: 'Tirupati', mandal: 'Srikalahasti', village: 'Srikalahasti' },
  ],
  telugu: [
    { district: 'అనకాపల్లి', mandal: 'అనకాపల్లి', village: 'అనకాపల్లి' },
    { district: 'అనకాపల్లి', mandal: 'యలమంచిలి', village: 'యలమంచిలి' },
    { district: 'కాకినాడ', mandal: 'కాకినాడ (పట్టణ)', village: 'కాకినాడ' },
    { district: 'కాకినాడ', mandal: 'పిఠాపురం', village: 'పిఠాపురం' },
    { district: 'ఎన్టీఆర్', mandal: 'విజయవాడ (పట్టణ)', village: 'విజయవాడ' },
    { district: 'ఎన్టీఆర్', mandal: 'తిరువూరు', village: 'తిరువూరు' },
    { district: 'పల్నాడు', mandal: 'నరసరావుపేట', village: 'నరసరావుపేట' },
    { district: 'తిరుపతి', mandal: 'తిరుపతి (పట్టణ)', village: 'తిరుపతి' },
    { district: 'తిరుపతి', mandal: 'శ్రీకాళహస్తి', village: 'శ్రీకాళహస్తి' },
  ],
};
